DROP TABLE IF EXISTS signer;
DROP TABLE IF EXISTS petition;

CREATE TABLE signer (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        first_name VARCHAR(100) NOT NULL,
                        last_name VARCHAR(100) NOT NULL,
                        email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE petition (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          title VARCHAR(255) NOT NULL,
                          description TEXT NOT NULL
);

CREATE TABLE petition_signer (
                                 petition_id BIGINT,
                                 signer_id BIGINT,
                                 PRIMARY KEY (petition_id, signer_id),
                                 FOREIGN KEY (petition_id) REFERENCES petition(id),
                                 FOREIGN KEY (signer_id) REFERENCES signer(id)
);